spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      #ddl-auto: create
      ddl-auto: update


